notify:
  description: QQ邮件通知提醒
  fields:
    message:
      name: message
      description: 邮件内容（可以为HTML格式和使用系统模板）
      example: '<b>当前时间： {{now()}} </b>'
      selector:
        text:
    title:
      name: title
      description: 邮件标题
      example: 消息来自HomeAssistant
      selector:
        text: